### ISSUE TITLE
compatibility with MariaDB 10.2  and PHP 7.1 

### ISSUE THREAD

**Issue by jf3218** [evilru/quake3-vsp-stats#1]
Possible to have a  fix  for Quake3-vsp-stats with MariaDB  and PHP 7.1 ?  
thx!

**Comment by evilru** [comment]
Hello,

As vsp-stats is pretty old, it used a very old version of adodb (3.50 19 May 2003)
I just updated the adodb lib to 5.20.10 (latest) and changed the corresponding config to make use of the now needed mysqli driver.
I don't have any game.log for testing right now - at least i was able to call it from the browser and it did not throw any PHP error...

Could you please give it a try and tell me if it works?
50a82222b150b92f5f6bbb625b9b2bdc6847ffa7

Cheers,
Martin

**Comment by jf3218** [comment]
Hello thanks you for the update,
  I did the test,  I'm now able to call it from the browser  but noting are showed, http://146.71.78.147/vsp/pub/themes/bismarck/index.php?config=cfg-default.php. 

When I go see my database ffa_vsp  with phpmyadmin   ther enoting have been created in ...  So yeah, I think the Stats dosen't read the game.log 
 
Best regards, 
jf.

**Comment by evilru** [comment]
Hm.. did you run the games.log import as described under point 3.c in the readme?

**Comment by jf3218** [comment]
Yes I did  via Power Shell http://prntscr.com/im9nv0   and via  the web  http://prntscr.com/im9par   http://prntscr.com/im9pgy

1- There noting get created into my  database  ffa_vsp  
2- You can see my database setting  in  cfg-default.php -   http://prntscr.com/im9swx
3- Here the game settings set to 'q3a'   - http://prntscr.com/im9ujh

I dont know why noting get create in the database,   maybe need to enable a option in the php.ini for adodb?

**Comment by jf3218** [comment]
Good job this working 👍   http://146.71.78.147/vsp-stats/pub/themes/bismarck/index.php

Small question: how  to show the adwards list    ?

**Comment by evilru** [comment]
Hm.. this worked for me.
Did you use the master branch?

I have the feeling it might relate to this change: https://github.com/evilru/quake3-vsp-stats/commit/692b27261afe2437ee986c30d0250152b6def0bc

**Comment by jf3218** [comment]
This was a mistake in my setting..  This working just fine now except for the flags...   Probally a other setting not set correctly .
