### ISSUE TITLE
DB connection fails on certain Docker engine versions

### ISSUE THREAD

**Issue by alcachofass** [evilru/quake3-vsp-stats#10]
"host.docker.internal" does not resolve on docker-20.10.4-1.amzn2.x86_64 running on Amazon Linux 2 AMI nor on docker-ce-20.10.7-3.el7.x86_64 on CentOS 7.9.2009. However, the service "db" should always resolve correctly through Docker's native DNS ensuring the connection to the DB always succeeds regardless of platform. (This issue does not affect Docker Desktop 20.10.6 on Windows 10 20H2.)

Example of Issue from inside a running instance of quake3-vsp-stats:
root@1f262848f947:/vsp# curl host.docker.internal
curl: (6) **Could not resolve host: host.docker.internal**
root@1f262848f947:/vsp# curl db
curl: (7) Failed to connect to db port 80: Connection refused
root@1f262848f947:/vsp#

I'll send you a PR #11  showing how I tackled this on the compose file. I _think_ the same could be accomplished by updating "ENV DB_HOSTNAME" in the Dockerfile.

**Comment by evilru** [comment]
Thank you for providing this information!
I updated the default value of DB_HOSTNAME
