### ISSUE TITLE
Does this work for MOHAA

### ISSUE THREAD

**Issue by hopper5** [evilru/quake3-vsp-stats#2]
Hello

I was wondering if this works for Medal of Honor?  I downloaded this one but after I run the stats using web browser (vsp.php) I get an error:  log type not recognized.  
The downloads on krilln site are corrupted and I cant find it anywhere else. 
Thanks

**Comment by MLSBraveHeart** [comment]
Yo Hopper, still having that issue? ;)

Seems to work on other server

**Comment by hopper5** [comment]
No.  It works now.  It was mistake on my part.  The country flags are not working however.  It says LOCATION UNKNOWN

**Comment by evilru** [comment]
Hello hopper5, thank you for the info regarding broken flags.
