### ISSUE TITLE
First seen 1971-12-28 23:59:59 

### ISSUE THREAD

**Issue by Lice2** [evilru/quake3-vsp-stats#5]
Hello, I have the problem that when I parse the Games.log with vsp, it says first seen by the user at First seen 1971-12-28 23:59:59.
With the game stats it is exactly like that at Time Start First seen 1971-12-28 23:59:59.
I am using the php 7.4.3 version.

**Comment by evilru** [comment]
Could you please try the steps described in #4 ?
Please tell me if it resolves your issue!

**Comment by Lice2** [comment]
Unfortunately that doesn't work for me. In vsp.php I have the line on $ V0f14082c ['parser-options'] = array (""); changed.
And in the Mysql database the command mysql> SET sql_mode = ''; executed.
Then I ran php vsp.php -l q3a games.log.
Then he started again 1971-12-28 23:59:59.

**Comment by evilru** [comment]
I will take a look into this - could you attach a games.log I can use for testing?

**Comment by Lice2** [comment]
Yes i do !
[games.log](https://github.com/evilru/quake3-vsp-stats/files/6086421/games.log)

**Comment by evilru** [comment]
Hello!
This was caused by the games.log I put there for testing - it was incomplete 🥴
I replaced it with a working one.

Just get the latest version as I did small fixes as well.

**Comment by Lice2** [comment]
Hmmm weird. When I use the new vsp in my Games.log I get
Analyzing game 0180 (86.84%) duplicated game timestamp,
.....
Analyzing game 0204 (99.96%) duplicated game timestamp, ignored

The new Games.log that is included works. 
Could it be because of my Games.log that there is no date and time? 
[games.log](https://github.com/evilru/quake3-vsp-stats/files/6134670/games.log)

**Comment by evilru** [comment]
This would make sense..
My games.log is from a server running osp - did you run any mods?

also die ioq3 versions used to create the log files are different:
- mine: **ioq3 1.36_GIT_c7ebe821-2018-08-02 linux-x86_64 Aug 16 2018**
- yours: **ioq3 1.36_GIT_05180e32-2020-12-26 linux-x86_64 Feb 21 2021**

these are the only differences I see

**Comment by Lice2** [comment]
No mods. Only the normal gamemode. Q3a. I have testet with osd. But same
problem no timestamp in the gameslog.

Martin Haberfellner ***@***.***> schrieb am Di., 16. März
2021, 15:11:

**Comment by Lice2** [comment]
Is there perhaps a certain setting or start command that then adds the server time to the Games.log?
I start my server like this: 
ioq3ded.x86_64 +set sv_punkbuster 0 +set fs_basepath /home/lice/Server/Quake3/ +set dedicated 2 +set net_ip $ip +set net_port $port +set logfile 3 +exec q3ded.cfg

**Comment by evilru** [comment]
It looks like vanilla q3a does not write any timestamps into the logfile.
I stepped through the code and have the feeling this never worked.

However, basically every server did run osp back then, why not give it a try?

You mentioned that the log files it produced when running osp did not work for you as well, did you pickup the right logfile from the osp folder?

**Comment by Lice2** [comment]
Ok with the OSP mod he writes the date in the Games.log
Thanks again for the help ! 

[games.log](https://github.com/evilru/quake3-vsp-stats/files/6163048/games.log)

**Comment by evilru** [comment]
You are welcome!
