### ISSUE TITLE
Removal of quake3-vsp-stats

### ISSUE THREAD

**Issue by drmuzic** [evilru/quake3-vsp-stats#6]
I wish there were a private way to do this but I cannot find an option to do such as there isn't an email posted. As stated in the user agreement this violates the Disclaimer/Legal Info/License Agreement as follows.

You may not:

    * permit other individuals to use the Software except under the terms listed
      here
    * **reverse engineer, disassemble, or create derivative works based on the
      Software for distribution or usage outside your web site excluding those
      applications described here**
    * modify and/or remove any copyright notices, links or labels on the Software
      on each page and in the header/footer of each script source file
    * **distribute modified versions of the Software**
    * distribute individual copies of files, libraries, or other programming
      material in the Software package
    * distribute or modify proprietary graphics, HTML, or CSS packaged with the
      Software for use in Software applications other than VSP or web sites
      without written permission from the author(s) of VSP.
    * use the Software in such as way as to condone or encourage terrorism,
      promote or provide pirated Software, or any other form of illegal or
      damaging activity

This is a request to remove quake3-vsp-stats due to miss match. Within the past two months a released v0.50 has been in the works and has been released 2/28/2021 at 11:45 PM . If you would like to contribute to V.S.P. our forums are open. I tried to get our project on here, but could not get the "pub" folder on here so I gave up on it.

http://www.krillinsworld.com/vsp | http://www.krillinsworld.com/forum/index.php#c9

Best Regards

**Comment by evilru** [comment]
Thank you for bringing this to my attention!

Since original author myrddin8@gmail.com has not had an issue with forks like yours (see screenshot below), I am operating under the assumption that they are okay with forks that keep the software operating. I only plan to do maintenance work, critical bug fixing but no functional modifications. 

However, I am happy to respond to and comply with requests from the original author myrddin8@gmail.com.
Best Regards

---

![image](https://user-images.githubusercontent.com/7511974/109965743-ae67d380-7cef-11eb-8d6e-097c84ad2543.png)

**Comment by drmuzic** [comment]
This is NOT a “fork.” We have been upkeeping V.S.P. since 2011. Myrddin has been unreachable since 2008! Therefor leaving this project abandoned. I have been with this project since 2004, shortly after it’s initial release, so I took it upon myself to take over V.S.P.  being as I have been keeping it up-to-date since! Because the original author is UNREACHABLE for unknown reasons I am next in line with this project. We can do this the hard way if you wish!?

Formally!
